version: '3.7'

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=answersapi
    ports:
      - 5432:5432

  answer-box-api:
    image: vivagelive/answers-api:1.0
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/answersapi?stringtype=unspecified
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - JWT_SECRET=secret

    depends_on:
      - 'postgres'
    restart: on-failure
